---
title: "Annotate MAF"
output: 
  html_notebook:
  toc: TRUE
toc_float: TRUE
author: Jo Lynne Rokita
params:
  maf_in:
    label: "MAF input file"
    value: data/snv-consensus-plus-hotspots.maf.tsv.gz
    input: file
  maf_goi:
    label: "goi MAF output file"
    value: results/snv-consensus-plus-hotspots-goi.maf.tsv
    input: file
---

```{r load libraries}
# load libraries
library(tidyverse)

# define directories 
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "oncokb-annotation")
input_dir <- file.path(analysis_dir, "input")
results_dir <- file.path(analysis_dir, "results")
data_dir <- file.path(root_dir, "data")

# If the input and results directories do not exist, create it
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

if (!dir.exists(input_dir)) {
  dir.create(input_dir, recursive = TRUE)
}

# add histologies file so we can subset maf
histologies_file <- file.path(root_dir, 
                           "analyses", 
                           "collapse-tumor-histologies", 
                           "results",
                           "germline-primary-plus-tumor-histologies-plot-groups-clin-meta.tsv")

# goi file
cpg_file <- file.path(analysis_dir, "input", "cpg.txt")
```


```{r load files}
tumor_ids <- read_tsv(histologies_file, guess_max = 3000) %>%
  pull(Kids_First_Biospecimen_ID_tumor)

cpgs <- read_lines(cpg_file)

maf <- data.table::fread(file.path(root_dir, params$maf_in), data.table = F) %>%
  filter(Tumor_Sample_Barcode %in% tumor_ids,
         Hugo_Symbol %in% cpgs) %>%
  unique() %>%
  write_tsv(file.path(analysis_dir, params$maf_goi))
```
