---
title: 'Query unfiltered variants in LFS and NF1 patients'
output: 
  html_document:
  toc: TRUE
toc_float: TRUE
author: Ryan Corbett
date: "2022-12-13"
---
  
  
Load libraries and set directory paths

```{r load libraries}
library(data.table)
library(tidyverse)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
setwd(root_dir)

data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "predisposition-variants")
results_dir <- file.path(analysis_dir, "results")
input_dir <- file.path(analysis_dir, "input")

lfs_chr17_unfiltered_dir <- file.path(input_dir, 'LFS_chr17_variants')
nf1_chr17_unfiltered_dir <- file.path(input_dir, 'NF1_chr17_variants')
```

Merge unfiltered TP53 variants calls from LFS patient chr17 variant files

```{r}
lfs_files <- list.files(lfs_chr17_unfiltered_dir)

for (i in 1:length(lfs_files)){
  if (i == 1){
    tp53_all <- read_tsv(paste0(lfs_chr17_unfiltered_dir, '/', lfs_files[i])) %>%
      filter(Hugo_symbol == 'TP53')
  }else{
    tp53 <- read_tsv(paste0(lfs_chr17_unfiltered_dir, '/', lfs_files[i])) %>%
      filter(Hugo_symbol == 'TP53')
    
    tp53_all <- tp53_all %>%
      bind_rows(tp53)
  }
}
```

Look at TP53 variant calls across in LFS patients

```{r}
table(tp53_all$`L-LP_Call_final`, tp53_all$Sub1.ID)

tp53_all %>%
  rename(Kids_First_Biospecimen_ID = Sub1.ID) %>%
  select(Kids_First_Biospecimen_ID, `L-LP_Call_final`, Hugo_symbol, HGVS.c, HGVS.p) %>%
  write_tsv(file.path(results_dir, 'all_tp53_variants_LFS_patients.tsv'))
```

Merge unfiltered NF1 variants in NF1 patient chr17 variant files

```{r}
nf1_files <- list.files(nf1_chr17_unfiltered_dir)

for (i in 1:length(nf1_files)){
  if (i == 1){
    nf1_all <- read_tsv(paste0(nf1_chr17_unfiltered_dir, '/', nf1_files[i])) %>%
      filter(Hugo_symbol == 'NF1')
  }else{
    nf1 <- read_tsv(paste0(nf1_chr17_unfiltered_dir, '/', nf1_files[i])) %>%
      filter(Hugo_symbol == 'NF1')
    
    nf1_all <- nf1_all %>%
      bind_rows(nf1)
  }
}
```

Look at NF1 variant calls across NF1 patients

```{r}
t(table(nf1_all$`L-LP_Call_final`, nf1_all$Sub1.ID))

nf1_all %>%
  rename(Kids_First_Biospecimen_ID = Sub1.ID) %>%
  select(Kids_First_Biospecimen_ID, `L-LP_Call_final`, Hugo_symbol, HGVS.c, HGVS.p) %>%
  write_tsv(file.path(results_dir, 'all_nf1_variants_NF1_patients.tsv'))
```
          
