---
title: "Annotate MAF"
output: 
  html_notebook:
  toc: TRUE
toc_float: TRUE
author: Jo Lynne Rokita
params:
  maf_in:
    label: "MAF input file"
    value: data/snv-consensus-plus-hotspots.maf.tsv.gz
    input: file
  maf_goi:
    label: "goi MAF file"
    value: results/snv-consensus-plus-hotspots-goi.maf.tsv
    input: file
  maf_out:
    label: "MAF output file"
    value: results/snv-consensus-plus-hotspots-goi-oncokb.maf.tsv
    input: file
  python_path:
    label: "Python path"
    #value: /usr/bin/python
    value: /Users/harenzaj/miniconda3/bin/python
    input: ""
---

```{r load libraries}
# load libraries
library(tidyverse)

# define directories 
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "oncokb-annotation")
input_dir <- file.path(analysis_dir, "input")
results_dir <- file.path(analysis_dir, "results")
data_dir <- file.path(root_dir, "data")

# If the input and results directories do not exist, create it
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

if (!dir.exists(input_dir)) {
  dir.create(input_dir, recursive = TRUE)
}

# oncokb binary
readRenviron("~/.Renviron")
oncokb_token <- Sys.getenv("oncokb_token")
oncokb_tool <- "~/oncokb-annotator"
maf_annotator <- file.path(oncokb_tool, "MafAnnotator.py")

# add histologies file so we can subset maf
histologies_file <- file.path(data_dir,"pbta-histologies.tsv")

# goi file
goi_file <- file.path(analysis_dir, "input", "cpg.txt")
```


```{r load files}
tumor_ids <- read_tsv(file.path(histologies_file), guess_max = 3000) %>%
  filter(!is.na(pathology_diagnosis),
                experimental_strategy != "RNA-Seq") %>%
  pull(Kids_First_Biospecimen_ID)

goi <- read_table(goi_file, col_names = "genes") %>%
  add_row(genes = "ATRX")

maf <- data.table::fread(file.path(root_dir, params$maf_in), data.table = F) %>%
  filter(Tumor_Sample_Barcode %in% tumor_ids,
         Hugo_Symbol %in% goi$genes) %>%
  unique() %>%
  write_tsv(file.path(analysis_dir, params$maf_goi))
```

```{r annotate pbta maf}
# pbta maf
command <- paste(params$python_path, maf_annotator, '-i', file.path(analysis_dir, params$maf_goi), '-o', file.path(analysis_dir, params$maf_out), '-b', oncokb_token, '-q hgvsp_short', '-r GRCh38')
#command

#system(command)
```




            