---
title: 'DNA repair pathway two-hits analysis'
output: 
  html_document:
  toc: TRUE
toc_float: TRUE
author: Ryan Corbett
date: "2022-12-14"
---

Load packages and set directories

```{r load libraries}
library(data.table)
library(tidyverse)
library(ggplot2)
library(ggsci)

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
setwd(root_dir)

data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "dna-repair-variant-summary")
results_dir <- file.path(analysis_dir, "results")
input_dir <- file.path(analysis_dir, "input")
plot_dir <- file.path(analysis_dir, "plots")

# If the input and results directories do not exist, create it
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}
```

# add histologies files so we can subset maf
```{r set file paths}
histologies_file <- file.path(root_dir,"analyses", "collapse-tumor-histologies", "results", "germline-primary-plus-tumor-histologies-CBTN-dx.tsv")

v22_hist_file <- file.path(data_dir,"pbta-histologies.tsv")

cpg_file <- file.path(root_dir, "analyses", "oncokb-annotation", "input", "cpg.txt")

plp_file <- file.path(results_dir, "dna_repair_germline_variant_plp.tsv")

somatic_file <- file.path(root_dir, 'analyses', 'two-hits', 'results', "pbta-oncokb-oncogenic-maf.tsv")

dna_repair_file <- file.path(input_dir, 'Knijnenburg_paper', 'dna_repair_all.txt')
```

Read in histology and gene list files
```{r read histologies}
v22_hist <- read_tsv(v22_hist_file, guess_max = 3000) %>%
  filter(!is.na(pathology_diagnosis),
         experimental_strategy == "WGS",
         tumor_descriptor != "Derived Cell Line")
integrated_hist <- read_tsv(histologies_file)

repair_genes <- read_tsv(dna_repair_file, col_names = F) %>%
  rename('genes' = X1)

cpgs <- read_tsv(cpg_file, col_names = F) %>%
  rename('genes' = X1)
```

Read in germline and somatic variant files

```{r read variant files}
germline <- read_tsv(plp_file) %>%
  dplyr::rename(Matched_Norm_Sample_Barcode = Kids_First_Biospecimen_ID,
                HGVSc_germ = HGVS.c,
                HGVSp_germ = HGVS.p) %>%
  filter(Hugo_Symbol %in% repair_genes$genes & Hugo_Symbol %in% cpgs$genes) %>%
  arrange(Matched_Norm_Sample_Barcode)

somatic <- read_tsv(somatic_file) %>%
  filter(Hugo_Symbol %in% repair_genes$genes & Hugo_Symbol %in% cpgs$genes) %>%
  mutate(VAF = t_alt_count / t_depth) %>%
  select(Matched_Norm_Sample_Barcode, Tumor_Sample_Barcode, Hugo_Symbol, Transcript_ID, HGVSc, HGVSp, VAF, SIFT, PolyPhen, Variant_Classification, HotSpotAllele, ONCOGENIC, MUTATION_EFFECT, VARIANT_IN_ONCOKB)
```

Identify occurrences of DNA repair gene germline variants and somatic mutations

```{r collapse germline somatic}
collapsed <- germline %>%
  dplyr::rename(Kids_First_Biospecimen_ID_normal = Matched_Norm_Sample_Barcode) %>%
  #mutate(path_call = paste(`L-LP_Call_final`, Reasoning_for_call, sep = ",")) %>%
  group_by(Kids_First_Biospecimen_ID_normal) %>%
  summarise(Hugo_Symbol = str_c(sort(unique(Hugo_Symbol)), collapse = "; "))  %>%
  left_join(integrated_hist)

collapsed_somatic <- somatic %>%
  dplyr::rename(Kids_First_Biospecimen_ID_normal = Matched_Norm_Sample_Barcode,
                Kids_First_Biospecimen_ID_tumor_maf = Tumor_Sample_Barcode,
                Hugo_Symbol_somatic = Hugo_Symbol) %>%
  group_by(Kids_First_Biospecimen_ID_normal, Kids_First_Biospecimen_ID_tumor_maf) %>%
  summarise(Hugo_Symbol_somatic = str_c(sort(unique(Hugo_Symbol_somatic)), collapse = "; "))

collapsed_germ_som <- collapsed %>%
  left_join(collapsed_somatic, by = "Kids_First_Biospecimen_ID_normal") %>%
  select(Kids_First_Participant_ID, Kids_First_Biospecimen_ID_normal, Hugo_Symbol,
         Kids_First_Biospecimen_ID_tumor_maf, Hugo_Symbol_somatic) %>%
  filter(!is.na(Kids_First_Biospecimen_ID_tumor_maf)) %>%
  write_tsv(file.path(results_dir, 'germline_somatic_DNArepair_pathway_second_hits.tsv'))
```