---
title: "Explore germline structural variant distributions"
output: html_notebook
author: Ryan Corbett
date: 2024
editor_options: 
  chunk_output_type: inline
---

# Load libraries
```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(tidyverse)
  library(ggpattern)
})

root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "germline-sv")
input_dir <- file.path(analysis_dir, "input")
plot_dir <- file.path(analysis_dir, "plots")
results_dir <- file.path(analysis_dir, "results")

source(file.path(root_dir, "figures", "theme.R"))
```

# Set file paths
```{r}

hist_file <- file.path(root_dir, 
                 "analyses", 
                 "collapse-tumor-histologies", 
                 "results",
                 "germline-primary-plus-tumor-histologies-plot-groups-clin-meta.tsv")

sv_plp_file <- file.path(input_dir, "pbta_germline_svs.tsv")


```

Load data
```{r}

sv_plp <- read_tsv(sv_plp_file)

hist <- read_tsv(hist_file)

```

Summarize structural variants by gene and sv type (deletion, duplication)
```{r}

table(sv_plp$Hugo_Symbol_cpg, sv_plp$Type)

```

# Join plp and hist data
```{r}

sv_plp <- sv_plp %>%
  left_join(hist[,c("Kids_First_Biospecimen_ID_normal", "plot_group")])

```

Create barplot of patient P/LP carrier count by CPG, histology, and SV type
```{r}

n_per_hist <- sv_plp %>%
  distinct(Kids_First_Biospecimen_ID_normal, Hugo_Symbol_cpg, .keep_all = T) %>%
  count(Hugo_Symbol_cpg, Type, plot_group) %>%
  dplyr::rename(hist_n = n)

  # create N per gene desc order for plot
n_per_gene <- sv_plp %>%
  distinct(Kids_First_Biospecimen_ID_normal, Hugo_Symbol_cpg, .keep_all = T) %>%
  left_join(hist, by = "Kids_First_Biospecimen_ID_normal") %>%
  count(Hugo_Symbol_cpg) %>%
  dplyr::rename(gene_n = n) %>%
  arrange(desc(gene_n)) %>%
  # create plot order desc by gene
  mutate(plot_order = row_number()) %>%
  # add back histology info
  left_join(n_per_hist) %>%
  left_join(hist[,c("plot_group", "plot_group_hex")]) %>%
  distinct()

  # palette
plot_group_palette <- n_per_gene$plot_group_hex
names(plot_group_palette) <- n_per_gene$plot_group

dist_plot <- ggplot(data = n_per_gene, aes(x = reorder(Hugo_Symbol_cpg, plot_order), y = hist_n, fill = plot_group, pattern = Type)) +
  geom_col_pattern(
    aes(pattern = Type),
    colour = "black",
    pattern_fill = "black",
    pattern_angle = 45,
    pattern_density = 0.1,
    pattern_spacing = 0.01,
  ) +
  scale_fill_manual(values = plot_group_palette, breaks = sort(names(plot_group_palette)),
                    guide = guide_legend(override.aes = list(pattern = "none"))) + 
  scale_pattern_manual(values = c(DUP = "stripe", DEL = "none"),
                       guide = guide_legend(override.aes = list(fill = "white"))) +
  ylab("Number of patients with P/LP CNV") +
  xlab("Cancer Predisposition Gene") +
  theme_Publication() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylim(0,5) +
  labs(fill = "Tumor diagnosis", pattern = "SV Type")

dist_plot

ggsave(file.path(plot_dir, "sv-plp-distribution-plot.tiff"),
       width = 7, height = 5, units = "in")

```