---
title: "Assess somatic CNVs for second hits"
output: 
  html_notebook:
  toc: TRUE
toc_float: TRUE
author: Ryan Corbett
---

This analysis identifies patients with germline P-LP variants in cancer predisposition genes that show subsequent seconds CNV hits in tumors. 

### Set libraries and file paths

```{r load libraries}
# load libraries
library(tidyverse)

# define directories 
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "two-hits")
results_dir <- file.path(analysis_dir, "results")
data_dir <- file.path(root_dir, "data")

# If the input and results directories do not exist, create it
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

# germline P-LP calls 
plp_file <- file.path(data_dir, "pbta_germline_plp_calls.tsv")

# add histologies file 
histologies_file <- file.path(root_dir,"analyses", "collapse-tumor-histologies", "results", "germline-primary-plus-tumor-histologies-plot-groups-clin-meta.tsv")

# cnv file with annotation 
cnv_file <- file.path(data_dir, "consensus_seg_annotated_cn_autosomes.tsv.gz")

# cpg file
cpg_file <- file.path(root_dir, "analyses", "oncokb-annotation", "input", "cpg.txt")
```

Read in PLP, histology, and cpg files. Subset P-LP calls to CPGs only and add histology

```{r}
# rename columns to specify germline
germline <- read_tsv(plp_file) %>%
  dplyr::rename(HGVSc_germ = HGVS.c,
                HGVSp_germ = HGVS.p) 

# renmae bs id column to match plp file
hist <- read_tsv(histologies_file) %>%
  rename("Kids_First_Biospecimen_ID" = "Kids_First_Biospecimen_ID_normal")

# CPGs
cpgs <- read_lines(cpg_file)

# filter PLP calls and add plot_group and molecular_subtype
germline <- germline %>%
  filter(Hugo_Symbol %in% cpgs) %>%
  left_join(hist[,c("Kids_First_Biospecimen_ID", "Kids_First_Biospecimen_ID_tumor",
                               "plot_group", "molecular_subtype")]) %>%
  select(Kids_First_Biospecimen_ID, Kids_First_Biospecimen_ID_tumor, 
         plot_group, molecular_subtype,
         Hugo_Symbol, `L-LP_Call_final`, Reasoning_for_call,
         HGVSc_germ, HGVSp_germ)
```

Identify patients with germline PLP variant and somatic CNV in same CPG

```{r}
# filter cnv to patients in cohort and CPG calls only
cnv <- read_tsv(cnv_file) %>%
  filter(biospecimen_id %in% hist$Kids_First_Biospecimen_ID_tumor & gene_symbol %in% cpgs) %>%
  rename("Hugo_Symbol" = gene_symbol,
         "Kids_First_Biospecimen_ID_tumor" = biospecimen_id,
         "CNV_status_somatic" = status,
         "copy_number_somatic" = copy_number,
         "ploidy_somatic" = "ploidy") %>%
  select(Hugo_Symbol, Kids_First_Biospecimen_ID_tumor,
         CNV_status_somatic, copy_number_somatic, ploidy_somatic)

# merge germline SNV and somatic CNV calls by bs and gene id
germline_somatic_gene_matches <- germline %>%
  inner_join(cnv, by = c("Kids_First_Biospecimen_ID_tumor", "Hugo_Symbol"))

germline_somatic_gene_matches
```

Save output

```{r save}
write_tsv(germline_somatic_gene_matches,
          file.path(results_dir, "germline-somatic-cnv-two-gene-hits.tsv"))
```