---
title: "Assess second hits"
output: 
  html_notebook:
  toc: TRUE
toc_float: TRUE
author: Jo Lynne Rokita
params:
  maf_in:
    label: "OncoKB-Annotated MAF input file"
    value: analyses/oncokb-annotation/results/snv-consensus-plus-hotspots-goi-oncokb.maf.tsv
    input: file
  germ_in:
    label: "germline file"
    value: data/pbta_germline_plp_calls.tsv
    input: file
editor_options: 
  chunk_output_type: inline
---
### Set libraries and file paths

```{r load libraries}
# load libraries
library(tidyverse)

# define directories 
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
analysis_dir <- file.path(root_dir, "analyses", "two-hits")
results_dir <- file.path(analysis_dir, "results")
data_dir <- file.path(root_dir, "data")

# If the input and results directories do not exist, create it
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

# add histologies file so we can subset maf
histologies_file <- file.path(root_dir,"analyses", "collapse-tumor-histologies", "results", "germline-primary-plus-tumor-histologies-CBTN-dx.tsv")

# remove cell lines from histologies file
v22_hist_file <- file.path(data_dir,"histologies.tsv")

# goi file
goi_file <- file.path(root_dir, "analyses", "oncokb-annotation", "input", "cpg.txt")
```

### Load oncokb annotated maf and explore data

```{r load files}
germline <- read_tsv(file.path(root_dir, params$germ_in)) %>%
  dplyr::rename(Matched_Norm_Sample_Barcode = Kids_First_Biospecimen_ID,
                HGVSc_germ = HGVS.c,
                HGVSp_germ = HGVS.p) 

integrated_hist <- read_tsv(histologies_file)
v22_hist <- read_tsv(v22_hist_file, guess_max = 3000) %>%
  filter(!is.na(pathology_diagnosis),
         experimental_strategy == "WGS",
         tumor_descriptor != "Derived Cell Line")

# CPGs
goi <- read_table(goi_file, col_names = "genes") #%>%

# load maf
maf <- data.table::fread(file.path(root_dir, params$maf_in), data.table = F) %>%
  filter(Tumor_Sample_Barcode %in% v22_hist$Kids_First_Biospecimen_ID)

# CPGs without somatic hits
setdiff(goi$genes, unique(maf$Hugo_Symbol))

# table of gene counts by oncogenic effect
maf %>%
  count(ONCOGENIC) %>%
  arrange(-n)

# filter known oncogenic/likely oncogenic/resistance hits
onco_hits <- maf %>%
  filter(ONCOGENIC %in% c("Likely Oncogenic", "Oncogenic", "Resistance")) %>%
  write_tsv(file.path(results_dir, "pbta-oncokb-oncogenic-maf.tsv"))

# prevalence by gene
onco_hits %>%
  count(Hugo_Symbol) %>%
  arrange(-n)

# prevalence by variant in oncokb
onco_hits %>%
  count(VARIANT_IN_ONCOKB) %>%
  arrange(-n)

# prevalence by variant in oncokb
onco_hits %>%
  count(MUTATION_EFFECT) %>%
  arrange(-n)

# how many are hotspots?
onco_hits %>%
  count(HotSpotAllele) %>%
  arrange(-n)

```

### Integrate with germline data

```{r two hits same gene}
# collapse calls a bit
onco_hits_subset <- onco_hits %>%
  mutate(VAF = t_alt_count / t_depth) %>%
  select(Matched_Norm_Sample_Barcode, Tumor_Sample_Barcode, Hugo_Symbol, Transcript_ID, HGVSc, HGVSp, VAF, SIFT, PolyPhen, Variant_Classification, HotSpotAllele, ONCOGENIC, MUTATION_EFFECT, VARIANT_IN_ONCOKB)

# two hit CPG matches
germline_somatic_gene_matches <- germline %>%
  inner_join(onco_hits_subset, by = c("Matched_Norm_Sample_Barcode", "Hugo_Symbol")) %>%
  write_tsv(file.path(results_dir, "germline-somatic-two-gene-hits.tsv"))
```

### List germline + somatic gene hits by sample

```{r gene hits by patient}
collapsed <- germline %>%
  dplyr::rename(Kids_First_Biospecimen_ID_normal = Matched_Norm_Sample_Barcode) %>%
  #mutate(path_call = paste(`L-LP_Call_final`, Reasoning_for_call, sep = ",")) %>%
  group_by(Kids_First_Biospecimen_ID_normal) %>%
  summarise(Hugo_Symbol = str_c(sort(unique(Hugo_Symbol)), collapse = "; ")) %>%
  left_join(integrated_hist)

collapsed_onco <- onco_hits_subset %>%
  dplyr::rename(Kids_First_Biospecimen_ID_normal = Matched_Norm_Sample_Barcode,
                Kids_First_Biospecimen_ID_tumor_maf = Tumor_Sample_Barcode,
                Hugo_Symbol_somatic = Hugo_Symbol) %>%
  group_by(Kids_First_Biospecimen_ID_normal, Kids_First_Biospecimen_ID_tumor_maf) %>%
  summarise(Hugo_Symbol_somatic = str_c(sort(unique(Hugo_Symbol_somatic)), collapse = "; "))


collapsed_germ_som <- collapsed %>%
  left_join(collapsed_onco, by = "Kids_First_Biospecimen_ID_normal") %>%
  write_tsv(file.path(results_dir, "germline-somatic-collapsed-by-gene.tsv"))

```

            